services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PORT: ${DB_PORT}
      POSTGRES_HOST: ${DB_HOST}
    ports:
      - 5432:5432

    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - ecommerce-network

volumes:
  postgres_data:

networks:
  ecommerce-network: